// Conditional tests
var favBook = "Peer e Kamil";
console.log("Is my favBook == \"Peer e Kamil ?  | I perdict \"True\" ");
console.log(favBook == "Peer e Kamil");
var favPlace = "Karachi";
var favFood = "Biryani";
var favCar = "Alto";
var favColor = "Black";
var favHobby = "Art";
var favDrink = "Coffee";
var favNum = "7";
var myProfession = "Teacher";
var myEdu = "Masters";
var myAge = "26";
console.log(favFood == "Biryani");
console.log(favCar == "Suzuki");
console.log(favColor == "Black");
console.log(favHobby == "Art");
console.log(favDrink == "Juice");
console.log(favNum == "6");
console.log(myProfession == "Doctor");
console.log(myAge == "26");
console.log(myEdu == "Masters");
console.log(favPlace == "Lahore");
